import {
    PartyPopper,
    CalendarHeart,
    Sparkles,
    Heart,
    Crown,
    Globe,
    Cake,
    Users,
    Baby,
    Gift,
    Flame,
    Moon,
    Sun,
    TreeDeciduous,
    GraduationCap,
    Home,
    Trophy,
} from "lucide-react";

export const categoryConfigs = {
    birthday: {
        title: "Birthday Templates",
        description: "handcrafted templates",
        icon: PartyPopper,
        gradient: "linear-gradient(135deg, #ec4899 0%, #f97316 100%)",
        bgGradient: "bg-gradient-to-br from-pink-50 via-rose-50/50 to-orange-50",
        categoryPrefix: "birthday-",
        activeColor: "pink",
        subcategories: [
            { id: "all", label: "All", category: "", icon: PartyPopper },
            { id: "girlfriend", label: "Girlfriend", category: "birthday-girlfriend", icon: Heart },
            { id: "boyfriend", label: "Boyfriend", category: "birthday-boyfriend", icon: Heart },
            { id: "mom", label: "Mom", category: "birthday-mom", icon: Gift },
            { id: "dad", label: "Dad", category: "birthday-dad", icon: Gift },
            { id: "sister", label: "Sister", category: "birthday-sister", icon: Users },
            { id: "brother", label: "Brother", category: "birthday-bro", icon: Users },
            { id: "kids", label: "Kids", category: "birthday-kids", icon: Baby },
            { id: "friend", label: "Friend", category: "birthday-friend", icon: Users },
        ],
    },
    anniversary: {
        title: "Anniversary Templates",
        description: "romantic templates",
        icon: CalendarHeart,
        gradient: "linear-gradient(135deg, #f43f5e 0%, #fb923c 100%)",
        bgGradient: "bg-gradient-to-br from-rose-50 via-pink-50/50 to-amber-50",
        categoryPrefix: "anniversary-",
        activeColor: "rose",
        subcategories: [
            { id: "all", label: "All", category: "", icon: CalendarHeart },
            { id: "romantic", label: "Romantic", category: "anniversary-romantic", icon: Heart },
            { id: "parents", label: "Parents", category: "anniversary-parents", icon: Users },
            { id: "couple", label: "Couple", category: "anniversary-couple", icon: Heart },
            { id: "spouse", label: "Spouse", category: "anniversary-spouse", icon: Heart },
        ],
    },
    wedding: {
        title: "Wedding Templates",
        description: "elegant templates",
        icon: Sparkles,
        gradient: "linear-gradient(135deg, #a855f7 0%, #ec4899 100%)",
        bgGradient: "bg-gradient-to-br from-purple-50 via-pink-50/50 to-rose-50",
        categoryPrefix: "wedding-",
        activeColor: "purple",
        subcategories: [
            { id: "all", label: "All", category: "", icon: Sparkles },
            { id: "grand", label: "Grand Wedding", category: "wedding-grand-wedding", icon: Crown },
            { id: "engagement", label: "Engagement", category: "wedding-engagement", icon: Heart },
            { id: "destination", label: "Destination", category: "wedding-destination", icon: Globe },
        ],
    },
    valentine: {
        title: "Valentine Week Templates",
        description: "romantic templates",
        icon: Heart,
        gradient: "linear-gradient(135deg, #ef4444 0%, #f43f5e 100%)",
        bgGradient: "bg-gradient-to-br from-red-50 via-rose-50/50 to-pink-50",
        categoryPrefix: "valentine-",
        activeColor: "red",
        subcategories: [
            { id: "all", label: "All Days", category: "", icon: Heart },
            { id: "valentines", label: "Valentine's Day", category: "valentine-valentines-day", icon: Heart },
            { id: "rose", label: "Rose Day", category: "valentine-rose-day", icon: Gift },
            { id: "propose", label: "Propose Day", category: "valentine-propose-day", icon: Heart },
            { id: "chocolate", label: "Chocolate Day", category: "valentine-chocolate-day", icon: Gift },
            { id: "teddy", label: "Teddy Day", category: "valentine-teddy-day", icon: Baby },
            { id: "promise", label: "Promise Day", category: "valentine-promise-day", icon: Heart },
            { id: "hug", label: "Hug Day", category: "valentine-hug-day", icon: Users },
            { id: "kiss", label: "Kiss Day", category: "valentine-kiss-day", icon: Heart },
        ],
    },
    special: {
        title: "Special Days",
        description: "milestone templates",
        icon: Crown,
        gradient: "linear-gradient(135deg, #6366f1 0%, #a855f7 100%)",
        bgGradient: "bg-gradient-to-br from-indigo-50 via-purple-50/50 to-pink-50",
        categoryPrefix: "special-",
        activeColor: "indigo",
        subcategories: [
            { id: "all", label: "All Events", category: "", icon: Crown },
            { id: "graduation", label: "Graduation", category: "special-graduation", icon: GraduationCap },
            { id: "baby-shower", label: "Baby Shower", category: "special-baby-shower", icon: Baby },
            { id: "housewarming", label: "Housewarming", category: "special-housewarming", icon: Home },
            { id: "achievement", label: "Achievement", category: "special-achievement", icon: Trophy },
            { id: "reunion", label: "Reunion", category: "special-reunion", icon: Users },
            { id: "thank-you", label: "Thank You", category: "special-thank-you", icon: Gift },
        ],
    },
    religious: {
        title: "Religious & Cultural",
        description: "festive templates",
        icon: Globe,
        gradient: "linear-gradient(135deg, #f97316 0%, #fb923c 100%)",
        bgGradient: "bg-gradient-to-br from-orange-50 via-amber-50/50 to-yellow-50",
        categoryPrefix: "religious-",
        activeColor: "orange",
        subcategories: [
            { id: "all", label: "All Festivals", category: "", icon: Globe },
            { id: "diwali", label: "Diwali", category: "religious-diwali", icon: Flame },
            { id: "eid", label: "Eid", category: "religious-eid", icon: Moon },
            { id: "christmas", label: "Christmas", category: "religious-christmas", icon: TreeDeciduous },
            { id: "holi", label: "Holi", category: "religious-holi", icon: Sparkles },
            { id: "navratri", label: "Navratri", category: "religious-navratri", icon: Crown },
            { id: "ganesh", label: "Ganesh Chaturthi", category: "religious-ganesh-chaturthi", icon: Sun },
            { id: "national", label: "National Days", category: "national-", icon: Globe },
        ],
    },
};
