"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'ko' | 'ar' | 'pt' | 'ru' | 'it' | 'tr' | 'nl' | 'pl' | 'th' | 'vi' | 'id' | 'bn' | 'ta' | 'mr' | 'te' | 'ur' | 'sw' | 'fa';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

type TranslationKey = keyof typeof translations.en;

const translations = {
    en: {
        'dashboard.hero.title': 'What will you design today?',
        'dashboard.hero.subtitle': 'Create stunning mini-websites and social media content for every special moment',
        'dashboard.web.title': 'My Website Orders',
        'dashboard.web.subtitle': 'Continue working on your saved website orders',
        'dashboard.templates.title': 'Mini Website Templates',
        'dashboard.templates.subtitle': 'Create beautiful interactive websites for your special occasions',
        'dashboard.posters.title': 'Poster & Story Templates',
        'dashboard.posters.subtitle': 'Design stunning social media posts and stories for Instagram, Facebook & WhatsApp',
        'dashboard.viewAll': 'View All',
        'dashboard.continueEditing': 'Continue Editing',
        'dashboard.preview': 'Preview',
        'dashboard.footer': 'Create beautiful digital experiences for life\'s special moments',
        'creator.brand': 'Creator Studio',
        'creator.brand.short': 'Creator',
        'sidebar.create': 'Create',
        'sidebar.home': 'Home',
        'sidebar.birthday': 'Birthday Website',
        'sidebar.anniversary': 'Anniversary Website',
        'sidebar.wedding': 'Wedding / Engagement',
        'sidebar.valentine': 'Valentine Week',
        'sidebar.special': 'Special Days',
        'sidebar.religious': 'Religious & Cultural',
        'sidebar.orders': 'Orders',
        'sidebar.profile': 'Edit Profile',
        'sidebar.logout': 'Log out',
        'birthday.title': 'Happy Birthday',
        'birthday.subtitle': 'My Love',
        'birthday.description': 'To the most beautiful soul who makes every day brighter',
        'countdown.title': 'Special Surprise Countdown',
        'memories.title': 'Our Beautiful Memories',
        'memories.subtitle': 'Every photo tells a story, every moment is a treasure',
        'timeline.title': 'My Love Letters',
        'timeline.subtitle': 'Every word comes straight from my heart',
        'button.save': 'Save',
        'button.publish': 'Publish',
        'button.draft': 'Draft',
        'nav.home': 'Home',
        'nav.orders': 'Orders',
        'nav.valentine': 'Valentine Week',
        'nav.birthday': 'Birthday',
        'nav.anniversary': 'Anniversary',
        'nav.special': 'Special Days',
        'nav.wedding': 'Wedding',
        'nav.cultural': 'Religious & Cultural',
    },
    hi: {
        'dashboard.hero.title': 'आज आप क्या डिज़ाइन करेंगे?',
        'dashboard.hero.subtitle': 'हर विशेष पल के लिए शानदार मिनी-वेबसाइट और सोशल मीडिया सामग्री बनाएं',
        'dashboard.web.title': 'मेरे वेबसाइट ऑर्डर',
        'dashboard.web.subtitle': 'अपने सहेजे गए वेबसाइट ऑर्डर पर काम जारी रखें',
        'dashboard.templates.title': 'मिनी वेबसाइट टेम्प्लेट',
        'dashboard.templates.subtitle': 'अपने विशेष अवसरों के लिए सुंदर इंटरैक्टिव वेबसाइट बनाएं',
        'dashboard.posters.title': 'पोस्टर और स्टोरी टेम्प्लेट',
        'dashboard.posters.subtitle': 'इंस्टाग्राम, फेसबुक और व्हाट्सएप के लिए शानदार सोशल मीडिया पोस्ट और कहानियां डिज़ाइन करें',
        'dashboard.viewAll': 'सभी देखें',
        'dashboard.continueEditing': 'संपादन जारी रखें',
        'dashboard.preview': 'पूर्वावलोकन',
        'dashboard.footer': 'जीवन के विशेष पलों के लिए सुंदर डिजिटल अनुभव बनाएं',
        'sidebar.create': 'बनाएं',
        'sidebar.home': 'होम',
        'sidebar.birthday': 'जन्मदिन वेबसाइट',
        'sidebar.anniversary': 'वर्षगांठ वेबसाइट',
        'sidebar.wedding': 'शादी / सगाई',
        'sidebar.valentine': 'वेलेंटाइन सप्ताह',
        'sidebar.special': 'विशेष दिन',
        'sidebar.religious': 'धार्मिक और सांस्कृतिक',
        'sidebar.orders': 'ऑर्डर',
        'sidebar.profile': 'प्रोफ़ाइल संपादित करें',
        'sidebar.logout': 'लॉग आउट',
        'birthday.title': 'जन्मदिन मुबारक हो',
        'birthday.subtitle': 'मेरा प्यार',
        'birthday.description': 'सबसे खूबसूरत आत्मा के लिए जो हर दिन को उज्ज्वल बनाता है',
        'countdown.title': 'विशेष आश्चर्य उलटी गिनती',
        'memories.title': 'हमारी सुंदर यादें',
        'memories.subtitle': 'हर तस्वीर एक कहानी कहती है, हर पल एक खजाना है',
        'timeline.title': 'मेरे प्रेम पत्र',
        'timeline.subtitle': 'हर शब्द सीधे मेरे दिल से आता है',
        'button.save': 'सहेजें',
        'button.publish': 'प्रकाशित करें',
        'button.draft': 'ड्राफ्ट',
        'nav.home': 'होम',
        'nav.orders': 'ऑर्डर',
        'nav.valentine': 'वेलेंटाइन सप्ताह',
        'nav.birthday': 'जन्मदिन',
        'nav.anniversary': 'वर्षगांठ',
        'nav.special': 'विशेष दिन',
        'nav.wedding': 'शादी',
        'nav.cultural': 'धार्मिक और सांस्कृतिक',
    },
    es: {
        'dashboard.hero.title': '¿Qué diseñarás hoy?',
        'dashboard.hero.subtitle': 'Crea mini sitios web impresionantes y contenido para redes sociales para cada momento especial',
        'dashboard.web.title': 'Mis pedidos de sitios web',
        'dashboard.web.subtitle': 'Continúa trabajando en tus pedidos de sitios web guardados',
        'dashboard.templates.title': 'Plantillas de mini sitios web',
        'dashboard.templates.subtitle': 'Crea hermosos sitios web interactivos para tus ocasiones especiales',
        'dashboard.posters.title': 'Plantillas de pósters e historias',
        'dashboard.posters.subtitle': 'Diseña impresionantes publicaciones e historias de redes sociales para Instagram, Facebook y WhatsApp',
        'dashboard.viewAll': 'Ver todo',
        'dashboard.continueEditing': 'Continuar editando',
        'dashboard.preview': 'Vista previa',
        'dashboard.footer': 'Crea hermosas experiencias digitales para los momentos especiales de la vida',
        'sidebar.create': 'Crear',
        'sidebar.home': 'Inicio',
        'sidebar.birthday': 'Sitio web de cumpleaños',
        'sidebar.anniversary': 'Sitio web de aniversario',
        'sidebar.wedding': 'Boda / Compromiso',
        'sidebar.valentine': 'Semana de San Valentín',
        'sidebar.special': 'Días especiales',
        'sidebar.religious': 'Religioso y cultural',
        'sidebar.orders': 'Pedidos',
        'sidebar.profile': 'Editar perfil',
        'sidebar.logout': 'Cerrar sesión',
        'birthday.title': 'Feliz Cumpleaños',
        'birthday.subtitle': 'Mi Amor',
        'birthday.description': 'Para el alma más hermosa que hace cada día más brillante',
        'countdown.title': 'Cuenta Regresiva Especial',
        'memories.title': 'Nuestros Hermosos Recuerdos',
        'memories.subtitle': 'Cada foto cuenta una historia, cada momento es un tesoro',
        'timeline.title': 'Mis Cartas de Amor',
        'timeline.subtitle': 'Cada palabra viene directamente de mi corazón',
        'button.save': 'Guardar',
        'button.publish': 'Publicar',
        'button.draft': 'Borrador',
        'nav.home': 'Inicio',
        'nav.orders': 'Pedidos',
        'nav.valentine': 'Semana de San Valentín',
        'nav.birthday': 'Cumpleaños',
        'nav.anniversary': 'Aniversario',
        'nav.special': 'Días Especiales',
        'nav.wedding': 'Boda',
        'nav.cultural': 'Religioso y Cultural',
    },
    fr: {
        'dashboard.hero.title': 'Que vas-tu concevoir aujourd\'hui ?',
        'dashboard.hero.subtitle': 'Créez de superbes mini-sites et du contenu pour les réseaux sociaux pour chaque moment spécial',
        'dashboard.web.title': 'Mes commandes de sites web',
        'dashboard.web.subtitle': 'Continuez à travailler sur vos commandes de sites web enregistrées',
        'dashboard.templates.title': 'Modèles de mini-sites',
        'dashboard.templates.subtitle': 'Créez de superbes sites web interactifs pour vos occasions spéciales',
        'dashboard.posters.title': 'Modèles d\'affiches et de stories',
        'dashboard.posters.subtitle': 'Concevez de superbes publications et stories pour Instagram, Facebook et WhatsApp',
        'dashboard.viewAll': 'Tout afficher',
        'dashboard.continueEditing': 'Continuer l\'édition',
        'dashboard.preview': 'Aperçu',
        'dashboard.footer': 'Créez de belles expériences numériques pour les moments spéciaux de la vie',
        'sidebar.create': 'Créer',
        'sidebar.home': 'Accueil',
        'sidebar.birthday': 'Site d\'anniversaire',
        'sidebar.anniversary': 'Site d\'anniversaire de mariage',
        'sidebar.wedding': 'Mariage / Fiançailles',
        'sidebar.valentine': 'Semaine de la Saint-Valentin',
        'sidebar.special': 'Jours spéciaux',
        'sidebar.religious': 'Religieux et culturel',
        'sidebar.orders': 'Commandes',
        'sidebar.profile': 'Éditer le profil',
        'sidebar.logout': 'Déconnexion',
        'birthday.title': 'Joyeux Anniversaire',
        'birthday.subtitle': 'Mon Amour',
        'birthday.description': "À l'âme la plus belle qui rend chaque jour plus lumineux",
        'countdown.title': 'Compte à Rebours Spécial',
        'memories.title': 'Nos Beaux Souvenirs',
        'memories.subtitle': 'Chaque photo raconte une histoire, chaque moment est un trésor',
        'timeline.title': 'Mes Lettres d\'Amour',
        'timeline.subtitle': 'Chaque mot vient directement de mon cœur',
        'button.save': 'Enregistrer',
        'button.publish': 'Publier',
        'button.draft': 'Brouillon',
        'nav.home': 'Accueil',
        'nav.orders': 'Commandes',
        'nav.valentine': 'Semaine de la Saint-Valentin',
        'nav.birthday': 'Anniversaire',
        'nav.anniversary': 'Anniversaire',
        'nav.special': 'Jours spéciaux',
        'nav.wedding': 'Mariage',
        'nav.cultural': 'Religieux et culturel',
    },
    de: {
        'dashboard.hero.title': 'Was wirst du heute gestalten?',
        'dashboard.hero.subtitle': 'Erstellen Sie atemberaubende Mini-Websites und Social-Media-Inhalte für jeden besonderen Moment',
        'dashboard.web.title': 'Meine Website-Bestellungen',
        'dashboard.web.subtitle': 'Arbeiten Sie weiter an Ihren gespeicherten Website-Bestellungen',
        'dashboard.templates.title': 'Mini-Website-Vorlagen',
        'dashboard.templates.subtitle': 'Erstellen Sie wunderschöne interaktive Websites für Ihre besonderen Anlässe',
        'dashboard.posters.title': 'Poster- und Story-Vorlagen',
        'dashboard.posters.subtitle': 'Gestalten Sie atemberaubende Social-Media-Posts und Stories für Instagram, Facebook & WhatsApp',
        'dashboard.viewAll': 'Alle ansehen',
        'dashboard.continueEditing': 'Weiter bearbeiten',
        'dashboard.preview': 'Vorschau',
        'dashboard.footer': 'Schaffen Sie wunderschöne digitale Erlebnisse für die besonderen Momente des Lebens',
        'sidebar.create': 'Erstellen',
        'sidebar.home': 'Home',
        'sidebar.birthday': 'Geburtstags-Website',
        'sidebar.anniversary': 'Jubiläums-Website',
        'sidebar.wedding': 'Hochzeit / Verlobung',
        'sidebar.valentine': 'Valentinswoche',
        'sidebar.special': 'Besondere Tage',
        'sidebar.religious': 'Religiös & Kulturell',
        'sidebar.orders': 'Bestellungen',
        'sidebar.profile': 'Profil bearbeiten',
        'sidebar.logout': 'Abmelden',
        'birthday.title': 'Alles Gute zum Geburtstag',
        'birthday.subtitle': 'Meine Liebe',
        'birthday.description': 'Für die schönste Seele, die jeden Tag heller macht',
        'countdown.title': 'Besonderer Überraschungs-Countdown',
        'memories.title': 'Unsere Schönen Erinnerungen',
        'memories.subtitle': 'Jedes Foto erzählt eine Geschichte, jeder Moment ist ein Schatz',
        'timeline.title': 'Meine Liebesbriefe',
        'timeline.subtitle': 'Jedes Wort kommt direkt aus meinem Herzen',
        'button.save': 'Speichern',
        'button.publish': 'Veröffentlichen',
        'button.draft': 'Entwurf',
        'nav.home': 'Startseite',
        'nav.orders': 'Bestellungen',
        'nav.valentine': 'Valentinswoche',
        'nav.birthday': 'Geburtstag',
        'nav.anniversary': 'Jubiläum',
        'nav.special': 'Besondere Tage',
        'nav.wedding': 'Hochzeit',
        'nav.cultural': 'Religiös und kulturell',
    },
    ar: {
        'dashboard.hero.title': 'ماذا ستصمم اليوم؟',
        'dashboard.hero.subtitle': 'أنشئ مواقع ويب صغيرة رائعة ومحتوى وسائل التواصل الاجتماعي لكل لحظة خاصة',
        'dashboard.web.title': 'طلبات موقع الويب الخاص بي',
        'dashboard.web.subtitle': 'تابع العمل على طلبات موقع الويب المحفوظة',
        'dashboard.templates.title': 'قوالب المواقع الصغيرة',
        'dashboard.templates.subtitle': 'أنشئ مواقع ويب تفاعلية جميلة لمناسباتك الخاصة',
        'dashboard.posters.title': 'قوالب الملصقات والقصص',
        'dashboard.posters.subtitle': 'صمم منشورات وقصص رائعة لوسائل التواصل الاجتماعي لإنستغرام وفيسبوك وواتساب',
        'dashboard.viewAll': 'عرض الكل',
        'dashboard.continueEditing': 'متابعة التحرير',
        'dashboard.preview': 'معاينة',
        'dashboard.footer': 'أنشئ تجارب رقمية جميلة للحظات الخاصة في الحياة',
        'sidebar.create': 'إنشاء',
        'sidebar.home': 'الرئيسية',
        'sidebar.birthday': 'موقع عيد الميلاد',
        'sidebar.anniversary': 'موقع الذكرى السنوية',
        'sidebar.wedding': 'الزفاف / الخطوبة',
        'sidebar.valentine': 'أسبوع عيد الحب',
        'sidebar.special': 'أيام خاصة',
        'sidebar.religious': 'ديني وثقافي',
        'sidebar.orders': 'الطلبات',
        'sidebar.profile': 'تعديل الملف الشخصي',
        'sidebar.logout': 'تسجيل الخروج',
        'birthday.title': 'عيد ميلاد سعيد',
        'birthday.subtitle': 'حبي',
        'birthday.description': 'إلى أجمل روح تجعل كل يوم أكثر إشراقاً',
        'countdown.title': 'العد التنازلي للمفاجأة الخاصة',
        'memories.title': 'ذكرياتنا الجميلة',
        'memories.subtitle': 'كل صورة تحكي قصة، كل لحظة كنز',
        'timeline.title': 'رسائل الحب الخاصة بي',
        'timeline.subtitle': 'كل كلمة تأتي مباشرة من قلبي',
        'button.save': 'حفظ',
        'button.publish': 'نشر',
        'button.draft': 'مسودة',
        'nav.home': 'الرئيسية',
        'nav.orders': 'الطلبات',
        'nav.valentine': 'أسبوع عيد الحب',
        'nav.birthday': 'عيد ميلاد',
        'nav.anniversary': 'الذكرى السنوية',
        'nav.special': 'أيام خاصة',
        'nav.wedding': 'زفاف',
        'nav.cultural': 'ديني وثقافي',
    },
    zh: {
        'dashboard.hero.title': '今天你要设计什么？',
        'dashboard.hero.subtitle': '为每个特殊时刻创建精美的迷你网站和社交媒体内容',
        'dashboard.web.title': '我的网站订单',
        'dashboard.web.subtitle': '继续处理您保存的网站订单',
        'dashboard.templates.title': '迷你网站模板',
        'dashboard.templates.subtitle': '为您的特殊场合创建精美的互动网站',
        'dashboard.posters.title': '海报和故事模板',
        'dashboard.posters.subtitle': '为Instagram、Facebook和WhatsApp设计精美的社交媒体帖子和故事',
        'dashboard.viewAll': '查看全部',
        'dashboard.continueEditing': '继续编辑',
        'dashboard.preview': '预览',
        'dashboard.footer': '为生活中的特殊时刻创造美好的数字体验',
        'sidebar.create': '创建',
        'sidebar.home': '首页',
        'sidebar.birthday': '生日网站',
        'sidebar.anniversary': '周年纪念网站',
        'sidebar.wedding': '婚礼/订婚',
        'sidebar.valentine': '情人节周',
        'sidebar.special': '特殊日子',
        'sidebar.religious': '宗教和文化',
        'sidebar.orders': '订单',
        'sidebar.profile': '编辑个人资料',
        'sidebar.logout': '登出',
        'birthday.title': '生日快乐',
        'birthday.subtitle': '我的爱',
        'birthday.description': '献给让每一天都更加光明的最美丽的灵魂',
        'countdown.title': '特别惊喜倒计时',
        'memories.title': '我们美好的回忆',
        'memories.subtitle': '每张照片都讲述一个故事，每个时刻都是宝藏',
        'timeline.title': '我的情书',
        'timeline.subtitle': '每个字都直接来自我的心',
        'button.save': '保存',
        'button.publish': '发布',
        'button.draft': '草稿',
        'nav.home': '首页',
        'nav.orders': '订单',
        'nav.valentine': '情人节周',
        'nav.birthday': '生日',
        'nav.anniversary': '周年纪念',
        'nav.special': '特殊日子',
        'nav.wedding': '婚礼',
        'nav.cultural': '宗教与文化',
    },
    pt: {
        'dashboard.hero.title': 'O que você vai criar hoje?',
        'dashboard.hero.subtitle': 'Crie mini sites impressionantes e conteúdo de mídia social para cada momento especial',
        'dashboard.web.title': 'Meus pedidos de sites',
        'dashboard.web.subtitle': 'Continue trabalhando em seus pedidos de sites salvos',
        'dashboard.templates.title': 'Modelos de mini sites',
        'dashboard.templates.subtitle': 'Crie lindos sites interativos para suas ocasiões especiais',
        'dashboard.posters.title': 'Modelos de pôsteres e stories',
        'dashboard.posters.subtitle': 'Crie posts e stories incríveis para Instagram, Facebook e WhatsApp',
        'dashboard.viewAll': 'Ver tudo',
        'dashboard.continueEditing': 'Continuar editando',
        'dashboard.preview': 'Visualizar',
        'dashboard.footer': 'Crie belas experiências digitais para os momentos especiais da vida',
        'sidebar.create': 'Criar',
        'sidebar.home': 'Início',
        'sidebar.birthday': 'Site de aniversário',
        'sidebar.anniversary': 'Site de aniversário de casamento',
        'sidebar.wedding': 'Casamento / Noivado',
        'sidebar.valentine': 'Semana dos Namorados',
        'sidebar.special': 'Dias especiais',
        'sidebar.religious': 'Religioso e cultural',
        'sidebar.orders': 'Pedidos',
        'sidebar.profile': 'Editar perfil',
        'sidebar.logout': 'Sair',
        'birthday.title': 'Feliz Aniversário',
        'birthday.subtitle': 'Meu Amor',
        'birthday.description': 'Para a alma mais linda que torna cada dia mais brilhante',
        'countdown.title': 'Contagem Regressiva Especial',
        'memories.title': 'Nossas Lindas Memórias',
        'memories.subtitle': 'Cada foto conta uma história, cada momento é um tesouro',
        'timeline.title': 'Minhas Cartas de Amor',
        'timeline.subtitle': 'Cada palavra vem diretamente do meu coração',
        'button.save': 'Salvar',
        'button.publish': 'Publicar',
        'button.draft': 'Rascunho',
        'nav.home': 'Início',
        'nav.orders': 'Pedidos',
        'nav.valentine': 'Semana dos Namorados',
        'nav.birthday': 'Aniversário',
        'nav.anniversary': 'Aniversário',
        'nav.special': 'Dias Especiais',
        'nav.wedding': 'Casamento',
        'nav.cultural': 'Religioso e Cultural',
    },
    bn: {
        'dashboard.hero.title': 'আজ আপনি কি ডিজাইন করবেন?',
        'dashboard.hero.subtitle': 'প্রতিটি বিশেষ মুহূর্তের জন্য অসাধারণ মিনি-ওয়েবসাইট এবং সোশ্যাল মিডিয়া কন্টেন্ট তৈরি করুন',
        'dashboard.web.title': 'আমার ওয়েবসাইট অর্ডার',
        'dashboard.web.subtitle': 'আপনার সংরক্ষিত ওয়েবসাইট অর্ডারে কাজ চালিয়ে যান',
        'dashboard.templates.title': 'মিনি ওয়েবসাইট টেমপ্লেট',
        'dashboard.templates.subtitle': 'আপনার বিশেষ অনুষ্ঠানের জন্য সুন্দর ইন্টারঅ্যাক্টিভ ওয়েবসাইট তৈরি করুন',
        'dashboard.posters.title': 'পোস্টার এবং স্টোরি টেমপ্লেট',
        'dashboard.posters.subtitle': 'Instagram, Facebook এবং WhatsApp এর জন্য অসাধারণ সোশ্যাল মিডিয়া পোস্ট এবং স্টোরি ডিজাইন করুন',
        'dashboard.viewAll': 'সব দেখুন',
        'dashboard.continueEditing': 'সম্পাদনা চালিয়ে যান',
        'dashboard.preview': 'প্রিভিউ',
        'dashboard.footer': 'জীবনের বিশেষ মুহূর্তের জন্য সুন্দর ডিজিটাল অভিজ্ঞতা তৈরি করুন',
        'sidebar.create': 'তৈরি করুন',
        'sidebar.home': 'হোম',
        'sidebar.birthday': 'জন্মদিন ওয়েবসাইট',
        'sidebar.anniversary': 'বার্ষিকী ওয়েবসাইট',
        'sidebar.wedding': 'বিবাহ / বাগদান',
        'sidebar.valentine': 'ভ্যালেন্টাইন সপ্তাহ',
        'sidebar.special': 'বিশেষ দিন',
        'sidebar.religious': 'ধর্মীয় এবং সাংস্কৃতিক',
        'sidebar.orders': 'অর্ডার',
        'sidebar.profile': 'প্রোফাইল সম্পাদনা করুন',
        'sidebar.logout': 'লগ আউট',
        'birthday.title': 'জন্মদিনের শুভেচ্ছা',
        'birthday.subtitle': 'আমার ভালোবাসা',
        'birthday.description': 'সবচেয়ে সুন্দর আত্মার জন্য যে প্রতিদিন উজ্জ্বল করে তোলে',
        'countdown.title': 'বিশেষ সারপ্রাইজ কাউন্টডাউন',
        'memories.title': 'আমাদের সুন্দর স্মৃতি',
        'memories.subtitle': 'প্রতিটি ছবি একটি গল্প বলে, প্রতিটি মুহূর্ত একটি ধন',
        'timeline.title': 'আমার প্রেমপত্র',
        'timeline.subtitle': 'প্রতিটি শব্দ সরাসরি আমার হৃদয় থেকে আসে',
        'button.save': 'সংরক্ষণ করুন',
        'button.publish': 'প্রকাশ করুন',
        'button.draft': 'খসড়া',
        'nav.home': 'হোম',
        'nav.orders': 'অর্ডার',
        'nav.valentine': 'ভ্যালেন্টাইন সপ্তাহ',
        'nav.birthday': 'জন্মদিন',
        'nav.anniversary': 'বার্ষিকী',
        'nav.special': 'বিশেষ দিন',
        'nav.wedding': 'বিয়ে',
        'nav.cultural': 'ধর্মীয় ও সাংস্কৃতিক',
    },
    ru: {
        'dashboard.hero.title': 'Что вы будете создавать сегодня?',
        'dashboard.hero.subtitle': 'Создавайте потрясающие мини-сайты и контент для социальных сетей для каждого особого момента',
        'dashboard.web.title': 'Мои заказы сайтов',
        'dashboard.web.subtitle': 'Продолжайте работу над сохраненными заказами сайтов',
        'dashboard.templates.title': 'Шаблоны мини-сайтов',
        'dashboard.templates.subtitle': 'Создавайте красивые интерактивные сайты для ваших особых случаев',
        'dashboard.posters.title': 'Шаблоны постеров и историй',
        'dashboard.posters.subtitle': 'Создавайте потрясающие посты и истории для Instagram, Facebook и WhatsApp',
        'dashboard.viewAll': 'Посмотреть все',
        'dashboard.continueEditing': 'Продолжить редактирование',
        'dashboard.preview': 'Предпросмотр',
        'dashboard.footer': 'Создавайте прекрасные цифровые впечатления для особых моментов жизни',
        'sidebar.create': 'Создать',
        'sidebar.home': 'Главная',
        'sidebar.birthday': 'Сайт дня рождения',
        'sidebar.anniversary': 'Сайт годовщины',
        'sidebar.wedding': 'Свадьба / Помолвка',
        'sidebar.valentine': 'Неделя Валентина',
        'sidebar.special': 'Особые дни',
        'sidebar.religious': 'Религиозное и культурное',
        'sidebar.orders': 'Заказы',
        'sidebar.profile': 'Редактировать профиль',
        'sidebar.logout': 'Выйти',
        'birthday.title': 'С Днем Рождения',
        'birthday.subtitle': 'Моя Любовь',
        'birthday.description': 'Для самой прекрасной души, которая делает каждый день ярче',
        'countdown.title': 'Особый Обратный Отсчет',
        'memories.title': 'Наши Прекрасные Воспоминания',
        'memories.subtitle': 'Каждая фотография рассказывает историю, каждый момент - сокровище',
        'timeline.title': 'Мои Любовные Письма',
        'timeline.subtitle': 'Каждое слово идет прямо из моего сердца',
        'button.save': 'Сохранить',
        'button.publish': 'Опубликовать',
        'button.draft': 'Черновик',
        'nav.home': 'Главная',
        'nav.orders': 'Заказы',
        'nav.valentine': 'Неделя святого Валентина',
        'nav.birthday': 'День рождения',
        'nav.anniversary': 'Юбилей',
        'nav.special': 'Особые дни',
        'nav.wedding': 'Свадьба',
        'nav.cultural': 'Религиозное и культурное',
    },
    ur: {
        'dashboard.hero.title': 'آج آپ کیا ڈیزائن کریں گے؟',
        'dashboard.hero.subtitle': 'ہر خاص لمحے کے لیے شاندار منی ویب سائٹس اور سوشل میڈیا مواد بنائیں',
        'dashboard.web.title': 'میرے ویب سائٹ آرڈرز',
        'dashboard.web.subtitle': 'اپنے محفوظ شدہ ویب سائٹ آرڈرز پر کام جاری رکھیں',
        'dashboard.templates.title': 'منی ویب سائٹ ٹیمپلیٹس',
        'dashboard.templates.subtitle': 'اپنے خاص مواقع کے لیے خوبصورت انٹرایکٹو ویب سائٹس بنائیں',
        'dashboard.posters.title': 'پوسٹر اور اسٹوری ٹیمپلیٹس',
        'dashboard.posters.subtitle': 'Instagram، Facebook اور WhatsApp کے لیے شاندار سوشل میڈیا پوسٹس اور اسٹوریز ڈیزائن کریں',
        'dashboard.viewAll': 'سب دیکھیں',
        'dashboard.continueEditing': 'ترمیم جاری رکھیں',
        'dashboard.preview': 'پیش نظارہ',
        'dashboard.footer': 'زندگی کے خاص لمحات کے لیے خوبصورت ڈیجیٹل تجربات بنائیں',
        'sidebar.create': 'بنائیں',
        'sidebar.home': 'ہوم',
        'sidebar.birthday': 'سالگرہ ویب سائٹ',
        'sidebar.anniversary': 'سالگرہ ویب سائٹ',
        'sidebar.wedding': 'شادی / منگنی',
        'sidebar.valentine': 'ویلنٹائن ہفتہ',
        'sidebar.special': 'خاص دن',
        'sidebar.religious': 'مذہبی اور ثقافتی',
        'sidebar.orders': 'آرڈرز',
        'sidebar.profile': 'پروفائل میں ترمیم کریں',
        'sidebar.logout': 'لاگ آؤٹ',
        'birthday.title': 'سالگرہ مبارک',
        'birthday.subtitle': 'میری محبت',
        'birthday.description': 'سب سے خوبصورت روح کے لیے جو ہر دن کو روشن بناتی ہے',
        'countdown.title': 'خاص سرپرائز الٹی گنتی',
        'memories.title': 'ہماری خوبصورت یادیں',
        'memories.subtitle': 'ہر تصویر ایک کہانی بیان کرتی ہے، ہر لمحہ ایک خزانہ ہے',
        'timeline.title': 'میرے محبت نامے',
        'timeline.subtitle': 'ہر لفظ براہ راست میرے دل سے آتا ہے',
        'button.save': 'محفوظ کریں',
        'button.publish': 'شائع کریں',
        'button.draft': 'مسودہ',
        'nav.home': 'ہوم',
        'nav.orders': 'آرڈرز',
        'nav.valentine': 'ویلنٹائن ہفتہ',
        'nav.birthday': 'سالگرہ',
        'nav.anniversary': 'سالگرہ',
        'nav.special': 'خاص دن',
        'nav.wedding': 'شادی',
        'nav.cultural': 'مذہبی اور ثقافتی',
    },
    id: {
        'dashboard.hero.title': 'Apa yang akan Anda desain hari ini?',
        'dashboard.hero.subtitle': 'Buat situs web mini dan konten media sosial yang menakjubkan untuk setiap momen spesial',
        'dashboard.web.title': 'Pesanan Situs Web Saya',
        'dashboard.web.subtitle': 'Lanjutkan mengerjakan pesanan situs web yang tersimpan',
        'dashboard.templates.title': 'Template Situs Web Mini',
        'dashboard.templates.subtitle': 'Buat situs web interaktif yang indah untuk acara spesial Anda',
        'dashboard.posters.title': 'Template Poster & Story',
        'dashboard.posters.subtitle': 'Desain postingan dan story media sosial yang menakjubkan untuk Instagram, Facebook & WhatsApp',
        'dashboard.viewAll': 'Lihat Semua',
        'dashboard.continueEditing': 'Lanjutkan Mengedit',
        'dashboard.preview': 'Pratinjau',
        'dashboard.footer': 'Ciptakan pengalaman digital yang indah untuk momen spesial dalam hidup',
        'sidebar.create': 'Buat',
        'sidebar.home': 'Beranda',
        'sidebar.birthday': 'Situs Web Ulang Tahun',
        'sidebar.anniversary': 'Situs Web Peringatan',
        'sidebar.wedding': 'Pernikahan / Pertunangan',
        'sidebar.valentine': 'Minggu Valentine',
        'sidebar.special': 'Hari Spesial',
        'sidebar.religious': 'Agama & Budaya',
        'sidebar.orders': 'Pesanan',
        'sidebar.profile': 'Edit Profil',
        'sidebar.logout': 'Keluar',
        'birthday.title': 'Selamat Ulang Tahun',
        'birthday.subtitle': 'Cintaku',
        'birthday.description': 'Untuk jiwa terindah yang membuat setiap hari lebih cerah',
        'countdown.title': 'Hitung Mundur Kejutan Spesial',
        'memories.title': 'Kenangan Indah Kita',
        'memories.subtitle': 'Setiap foto menceritakan sebuah kisah, setiap momen adalah harta',
        'timeline.title': 'Surat Cinta Saya',
        'timeline.subtitle': 'Setiap kata datang langsung dari hati saya',
        'button.save': 'Simpan',
        'button.publish': 'Terbitkan',
        'button.draft': 'Draf',
        'nav.home': 'Beranda',
        'nav.orders': 'Pesanan',
        'nav.valentine': 'Minggu Valentine',
        'nav.birthday': 'Ulang Tahun',
        'nav.anniversary': 'Peringatan',
        'nav.special': 'Hari Istimewa',
        'nav.wedding': 'Pernikahan',
        'nav.cultural': 'Keagamaan & Budaya',
    },
    te: {
        'dashboard.hero.title': 'ఈరోజు మీరు ఏమి డిజైన్ చేస్తారు?',
        'dashboard.hero.subtitle': 'ప్రతి ప్రత్యేక క్షణం కోసం అద్భుతమైన మినీ-వెబ్‌సైట్‌లు మరియు సోషల్ మీడియా కంటెంట్‌ను సృష్టించండి',
        'dashboard.web.title': 'నా వెబ్‌సైట్ ఆర్డర్‌లు',
        'dashboard.web.subtitle': 'మీ సేవ్ చేసిన వెబ్‌సైట్ ఆర్డర్‌లపై పని కొనసాగించండి',
        'dashboard.templates.title': 'మినీ వెబ్‌సైట్ టెంప్లేట్‌లు',
        'dashboard.templates.subtitle': 'మీ ప్రత్యేక సందర్భాల కోసం అందమైన ఇంటరాక్టివ్ వెబ్‌సైట్‌లను సృష్టించండి',
        'dashboard.posters.title': 'పోస్టర్ & స్టోరీ టెంప్లేట్‌లు',
        'dashboard.posters.subtitle': 'Instagram, Facebook & WhatsApp కోసం అద్భుతమైన సోషల్ మీడియా పోస్ట్‌లు మరియు స్టోరీలను డిజైన్ చేయండి',
        'dashboard.viewAll': 'అన్నీ చూడండి',
        'dashboard.continueEditing': 'ఎడిటింగ్ కొనసాగించండి',
        'dashboard.preview': 'ప్రివ్యూ',
        'dashboard.footer': 'జీవితంలోని ప్రత్యేక క్షణాల కోసం అందమైన డిజిటల్ అనుభవాలను సృష్టించండి',
        'creator.brand': 'క్రియేటర్ స్టూడియో',
        'creator.brand.short': 'క్రియేటర్',
        'sidebar.create': 'సృష్టించండి',
        'sidebar.home': 'హోమ్',
        'sidebar.birthday': 'పుట్టినరోజు వెబ్‌సైట్',
        'sidebar.anniversary': 'వార్షికోత్సవ వెబ్‌సైట్',
        'sidebar.wedding': 'పెళ్లి / నిశ్చితార్థం',
        'sidebar.valentine': 'వాలెంటైన్ వారం',
        'sidebar.special': 'ప్రత్యేక రోజులు',
        'sidebar.religious': 'మత & సాంస్కృతిక',
        'sidebar.orders': 'ఆర్డర్‌లు',
        'sidebar.profile': 'ప్రొఫైల్ సవరించండి',
        'sidebar.logout': 'లాగ్ అవుట్',
        'birthday.title': 'పుట్టినరోజు శుభాకాంక్షలు',
        'birthday.subtitle': 'నా ప్రేమ',
        'birthday.description': 'ప్రతి రోజును ప్రకాశవంతం చేసే అత్యంత అందమైన ఆత్మకు',
        'countdown.title': 'ప్రత్యేక ఆశ్చర్య కౌంట్‌డౌన్',
        'memories.title': 'మన అందమైన జ్ఞాపకాలు',
        'memories.subtitle': 'ప్రతి ఫోటో ఒక కథను చెబుతుంది, ప్రతి క్షణం ఒక నిధి',
        'timeline.title': 'నా ప్రేమ లేఖలు',
        'timeline.subtitle': 'ప్రతి పదం నా గుండె నుండి నేరుగా వస్తుంది',
        'button.save': 'సేవ్ చేయండి',
        'button.publish': 'ప్రచురించండి',
        'button.draft': 'డ్రాఫ్ట్',
        'nav.home': 'హోమ్',
        'nav.orders': 'ఆర్డర్లు',
        'nav.valentine': 'వాలెంటైన్ వారం',
        'nav.birthday': 'పుట్టినరోజు',
        'nav.anniversary': 'వార్షికోత్సవం',
        'nav.special': 'ప్రత్యేక దినాలు',
        'nav.wedding': 'పెళ్ళి',
        'nav.cultural': 'మత మరియు సాంస్కృతిక',
    },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        // Load saved language from localStorage
        const saved = localStorage.getItem('preferred_language') as Language;
        if (saved && translations[saved as keyof typeof translations]) {
            setLanguageState(saved);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('preferred_language', lang);
    };

    const t = (key: string): string => {
        const langData = translations as Record<string, Record<string, string>>;
        const langTranslations = langData[language];

        if (langTranslations && langTranslations[key]) {
            return langTranslations[key];
        }

        // Fallback to English
        const enTranslations = translations.en as Record<string, string>;
        return enTranslations[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}
